name: Makefile CI

on:
  push:
    branches: [ openwrt-21.02 ]
  pull_request:
    branches: [ openwrt-21.02 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: prepare
      run: |
          ./prebuild-common.sh
    - name: config
      run: cp ./config-r4s .config
      
    - name: Install dependencies
      run: |
          make defconfig
          make download -j8
          make download -j8
          make -j8
